apiVersion: network.azure.crossplane.io/v1alpha3
kind: PublicIPAddress
metadata:
  name: example-public-ip-address
spec:
  forProvider:
    resourceGroupNameRef:
      name: example-rg
    allocationMethod: Static
    version: IPv4
    sku:
      name: Standard
    location: West US 2
    tcpIdleTimeoutInMinutes: 5
    dnsSettings:
      domainNameLabel: crossplane-example
# Looks like the following requires the feature "Microsoft.Network/AllowBringYourOwnPublicIpAddress" to be registered for the subscription
#    ipTags:
#      - ipTagType: FirstPartyUsage
#        tag: Storage
    tags:
      application: crossplane
  providerConfigRef:
    name: example
