//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointObservation) DeepCopyInto(out *EndpointObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointObservation.
func (in *EndpointObservation) DeepCopy() *EndpointObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointParameters) DeepCopyInto(out *EndpointParameters) {
	*out = *in
	if in.BatchFrequencyInSeconds != nil {
		in, out := &in.BatchFrequencyInSeconds, &out.BatchFrequencyInSeconds
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.ContainerNameRef != nil {
		in, out := &in.ContainerNameRef, &out.ContainerNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ContainerNameSelector != nil {
		in, out := &in.ContainerNameSelector, &out.ContainerNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(string)
		**out = **in
	}
	if in.FileNameFormat != nil {
		in, out := &in.FileNameFormat, &out.FileNameFormat
		*out = new(string)
		**out = **in
	}
	if in.MaxChunkSizeInBytes != nil {
		in, out := &in.MaxChunkSizeInBytes, &out.MaxChunkSizeInBytes
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointParameters.
func (in *EndpointParameters) DeepCopy() *EndpointParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrichmentObservation) DeepCopyInto(out *EnrichmentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrichmentObservation.
func (in *EnrichmentObservation) DeepCopy() *EnrichmentObservation {
	if in == nil {
		return nil
	}
	out := new(EnrichmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrichmentParameters) DeepCopyInto(out *EnrichmentParameters) {
	*out = *in
	if in.EndpointNames != nil {
		in, out := &in.EndpointNames, &out.EndpointNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrichmentParameters.
func (in *EnrichmentParameters) DeepCopy() *EnrichmentParameters {
	if in == nil {
		return nil
	}
	out := new(EnrichmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackRouteObservation) DeepCopyInto(out *FallbackRouteObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackRouteObservation.
func (in *FallbackRouteObservation) DeepCopy() *FallbackRouteObservation {
	if in == nil {
		return nil
	}
	out := new(FallbackRouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackRouteParameters) DeepCopyInto(out *FallbackRouteParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EndpointNames != nil {
		in, out := &in.EndpointNames, &out.EndpointNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackRouteParameters.
func (in *FallbackRouteParameters) DeepCopy() *FallbackRouteParameters {
	if in == nil {
		return nil
	}
	out := new(FallbackRouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileUploadObservation) DeepCopyInto(out *FileUploadObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileUploadObservation.
func (in *FileUploadObservation) DeepCopy() *FileUploadObservation {
	if in == nil {
		return nil
	}
	out := new(FileUploadObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileUploadParameters) DeepCopyInto(out *FileUploadParameters) {
	*out = *in
	out.ConnectionStringSecretRef = in.ConnectionStringSecretRef
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.DefaultTTL != nil {
		in, out := &in.DefaultTTL, &out.DefaultTTL
		*out = new(string)
		**out = **in
	}
	if in.LockDuration != nil {
		in, out := &in.LockDuration, &out.LockDuration
		*out = new(string)
		**out = **in
	}
	if in.MaxDeliveryCount != nil {
		in, out := &in.MaxDeliveryCount, &out.MaxDeliveryCount
		*out = new(float64)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(bool)
		**out = **in
	}
	if in.SASTTL != nil {
		in, out := &in.SASTTL, &out.SASTTL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileUploadParameters.
func (in *FileUploadParameters) DeepCopy() *FileUploadParameters {
	if in == nil {
		return nil
	}
	out := new(FileUploadParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHub) DeepCopyInto(out *IOTHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHub.
func (in *IOTHub) DeepCopy() *IOTHub {
	if in == nil {
		return nil
	}
	out := new(IOTHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroup) DeepCopyInto(out *IOTHubConsumerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroup.
func (in *IOTHubConsumerGroup) DeepCopy() *IOTHubConsumerGroup {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubConsumerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroupList) DeepCopyInto(out *IOTHubConsumerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubConsumerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroupList.
func (in *IOTHubConsumerGroupList) DeepCopy() *IOTHubConsumerGroupList {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubConsumerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroupObservation) DeepCopyInto(out *IOTHubConsumerGroupObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroupObservation.
func (in *IOTHubConsumerGroupObservation) DeepCopy() *IOTHubConsumerGroupObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroupParameters) DeepCopyInto(out *IOTHubConsumerGroupParameters) {
	*out = *in
	if in.EventHubEndpointName != nil {
		in, out := &in.EventHubEndpointName, &out.EventHubEndpointName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubName != nil {
		in, out := &in.IOTHubName, &out.IOTHubName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubNameRef != nil {
		in, out := &in.IOTHubNameRef, &out.IOTHubNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTHubNameSelector != nil {
		in, out := &in.IOTHubNameSelector, &out.IOTHubNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroupParameters.
func (in *IOTHubConsumerGroupParameters) DeepCopy() *IOTHubConsumerGroupParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroupSpec) DeepCopyInto(out *IOTHubConsumerGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroupSpec.
func (in *IOTHubConsumerGroupSpec) DeepCopy() *IOTHubConsumerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubConsumerGroupStatus) DeepCopyInto(out *IOTHubConsumerGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubConsumerGroupStatus.
func (in *IOTHubConsumerGroupStatus) DeepCopy() *IOTHubConsumerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubConsumerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPS) DeepCopyInto(out *IOTHubDPS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPS.
func (in *IOTHubDPS) DeepCopy() *IOTHubDPS {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificate) DeepCopyInto(out *IOTHubDPSCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificate.
func (in *IOTHubDPSCertificate) DeepCopy() *IOTHubDPSCertificate {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPSCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificateList) DeepCopyInto(out *IOTHubDPSCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubDPSCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificateList.
func (in *IOTHubDPSCertificateList) DeepCopy() *IOTHubDPSCertificateList {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPSCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificateObservation) DeepCopyInto(out *IOTHubDPSCertificateObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificateObservation.
func (in *IOTHubDPSCertificateObservation) DeepCopy() *IOTHubDPSCertificateObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificateParameters) DeepCopyInto(out *IOTHubDPSCertificateParameters) {
	*out = *in
	out.CertificateContentSecretRef = in.CertificateContentSecretRef
	if in.IOTDPSName != nil {
		in, out := &in.IOTDPSName, &out.IOTDPSName
		*out = new(string)
		**out = **in
	}
	if in.IOTDPSNameRef != nil {
		in, out := &in.IOTDPSNameRef, &out.IOTDPSNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTDPSNameSelector != nil {
		in, out := &in.IOTDPSNameSelector, &out.IOTDPSNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificateParameters.
func (in *IOTHubDPSCertificateParameters) DeepCopy() *IOTHubDPSCertificateParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificateSpec) DeepCopyInto(out *IOTHubDPSCertificateSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificateSpec.
func (in *IOTHubDPSCertificateSpec) DeepCopy() *IOTHubDPSCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSCertificateStatus) DeepCopyInto(out *IOTHubDPSCertificateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSCertificateStatus.
func (in *IOTHubDPSCertificateStatus) DeepCopy() *IOTHubDPSCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSList) DeepCopyInto(out *IOTHubDPSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubDPS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSList.
func (in *IOTHubDPSList) DeepCopy() *IOTHubDPSList {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSObservation) DeepCopyInto(out *IOTHubDPSObservation) {
	*out = *in
	if in.DeviceProvisioningHostName != nil {
		in, out := &in.DeviceProvisioningHostName, &out.DeviceProvisioningHostName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDScope != nil {
		in, out := &in.IDScope, &out.IDScope
		*out = new(string)
		**out = **in
	}
	if in.ServiceOperationsHostName != nil {
		in, out := &in.ServiceOperationsHostName, &out.ServiceOperationsHostName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSObservation.
func (in *IOTHubDPSObservation) DeepCopy() *IOTHubDPSObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSParameters) DeepCopyInto(out *IOTHubDPSParameters) {
	*out = *in
	if in.AllocationPolicy != nil {
		in, out := &in.AllocationPolicy, &out.AllocationPolicy
		*out = new(string)
		**out = **in
	}
	if in.LinkedHub != nil {
		in, out := &in.LinkedHub, &out.LinkedHub
		*out = make([]LinkedHubParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = make([]IOTHubDPSSkuParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSParameters.
func (in *IOTHubDPSParameters) DeepCopy() *IOTHubDPSParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicy) DeepCopyInto(out *IOTHubDPSSharedAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicy.
func (in *IOTHubDPSSharedAccessPolicy) DeepCopy() *IOTHubDPSSharedAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPSSharedAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicyList) DeepCopyInto(out *IOTHubDPSSharedAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubDPSSharedAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicyList.
func (in *IOTHubDPSSharedAccessPolicyList) DeepCopy() *IOTHubDPSSharedAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubDPSSharedAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicyObservation) DeepCopyInto(out *IOTHubDPSSharedAccessPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicyObservation.
func (in *IOTHubDPSSharedAccessPolicyObservation) DeepCopy() *IOTHubDPSSharedAccessPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicyParameters) DeepCopyInto(out *IOTHubDPSSharedAccessPolicyParameters) {
	*out = *in
	if in.EnrollmentRead != nil {
		in, out := &in.EnrollmentRead, &out.EnrollmentRead
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentWrite != nil {
		in, out := &in.EnrollmentWrite, &out.EnrollmentWrite
		*out = new(bool)
		**out = **in
	}
	if in.IOTHubDPSName != nil {
		in, out := &in.IOTHubDPSName, &out.IOTHubDPSName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubDPSNameRef != nil {
		in, out := &in.IOTHubDPSNameRef, &out.IOTHubDPSNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTHubDPSNameSelector != nil {
		in, out := &in.IOTHubDPSNameSelector, &out.IOTHubDPSNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistrationRead != nil {
		in, out := &in.RegistrationRead, &out.RegistrationRead
		*out = new(bool)
		**out = **in
	}
	if in.RegistrationWrite != nil {
		in, out := &in.RegistrationWrite, &out.RegistrationWrite
		*out = new(bool)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceConfig != nil {
		in, out := &in.ServiceConfig, &out.ServiceConfig
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicyParameters.
func (in *IOTHubDPSSharedAccessPolicyParameters) DeepCopy() *IOTHubDPSSharedAccessPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicySpec) DeepCopyInto(out *IOTHubDPSSharedAccessPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicySpec.
func (in *IOTHubDPSSharedAccessPolicySpec) DeepCopy() *IOTHubDPSSharedAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSharedAccessPolicyStatus) DeepCopyInto(out *IOTHubDPSSharedAccessPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSharedAccessPolicyStatus.
func (in *IOTHubDPSSharedAccessPolicyStatus) DeepCopy() *IOTHubDPSSharedAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSharedAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSkuObservation) DeepCopyInto(out *IOTHubDPSSkuObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSkuObservation.
func (in *IOTHubDPSSkuObservation) DeepCopy() *IOTHubDPSSkuObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSkuObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSkuParameters) DeepCopyInto(out *IOTHubDPSSkuParameters) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSkuParameters.
func (in *IOTHubDPSSkuParameters) DeepCopy() *IOTHubDPSSkuParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSkuParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSSpec) DeepCopyInto(out *IOTHubDPSSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSSpec.
func (in *IOTHubDPSSpec) DeepCopy() *IOTHubDPSSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubDPSStatus) DeepCopyInto(out *IOTHubDPSStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubDPSStatus.
func (in *IOTHubDPSStatus) DeepCopy() *IOTHubDPSStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubDPSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainer) DeepCopyInto(out *IOTHubEndpointStorageContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainer.
func (in *IOTHubEndpointStorageContainer) DeepCopy() *IOTHubEndpointStorageContainer {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubEndpointStorageContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainerList) DeepCopyInto(out *IOTHubEndpointStorageContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubEndpointStorageContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainerList.
func (in *IOTHubEndpointStorageContainerList) DeepCopy() *IOTHubEndpointStorageContainerList {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubEndpointStorageContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainerObservation) DeepCopyInto(out *IOTHubEndpointStorageContainerObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainerObservation.
func (in *IOTHubEndpointStorageContainerObservation) DeepCopy() *IOTHubEndpointStorageContainerObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainerParameters) DeepCopyInto(out *IOTHubEndpointStorageContainerParameters) {
	*out = *in
	if in.BatchFrequencyInSeconds != nil {
		in, out := &in.BatchFrequencyInSeconds, &out.BatchFrequencyInSeconds
		*out = new(float64)
		**out = **in
	}
	out.ConnectionStringSecretRef = in.ConnectionStringSecretRef
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.ContainerNameRef != nil {
		in, out := &in.ContainerNameRef, &out.ContainerNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ContainerNameSelector != nil {
		in, out := &in.ContainerNameSelector, &out.ContainerNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(string)
		**out = **in
	}
	if in.FileNameFormat != nil {
		in, out := &in.FileNameFormat, &out.FileNameFormat
		*out = new(string)
		**out = **in
	}
	if in.IOTHubName != nil {
		in, out := &in.IOTHubName, &out.IOTHubName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubNameRef != nil {
		in, out := &in.IOTHubNameRef, &out.IOTHubNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTHubNameSelector != nil {
		in, out := &in.IOTHubNameSelector, &out.IOTHubNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxChunkSizeInBytes != nil {
		in, out := &in.MaxChunkSizeInBytes, &out.MaxChunkSizeInBytes
		*out = new(float64)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainerParameters.
func (in *IOTHubEndpointStorageContainerParameters) DeepCopy() *IOTHubEndpointStorageContainerParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainerSpec) DeepCopyInto(out *IOTHubEndpointStorageContainerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainerSpec.
func (in *IOTHubEndpointStorageContainerSpec) DeepCopy() *IOTHubEndpointStorageContainerSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubEndpointStorageContainerStatus) DeepCopyInto(out *IOTHubEndpointStorageContainerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubEndpointStorageContainerStatus.
func (in *IOTHubEndpointStorageContainerStatus) DeepCopy() *IOTHubEndpointStorageContainerStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubEndpointStorageContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRoute) DeepCopyInto(out *IOTHubFallbackRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRoute.
func (in *IOTHubFallbackRoute) DeepCopy() *IOTHubFallbackRoute {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubFallbackRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRouteList) DeepCopyInto(out *IOTHubFallbackRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubFallbackRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRouteList.
func (in *IOTHubFallbackRouteList) DeepCopy() *IOTHubFallbackRouteList {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubFallbackRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRouteObservation) DeepCopyInto(out *IOTHubFallbackRouteObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRouteObservation.
func (in *IOTHubFallbackRouteObservation) DeepCopy() *IOTHubFallbackRouteObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRouteParameters) DeepCopyInto(out *IOTHubFallbackRouteParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EndpointNames != nil {
		in, out := &in.EndpointNames, &out.EndpointNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EndpointNamesRefs != nil {
		in, out := &in.EndpointNamesRefs, &out.EndpointNamesRefs
		*out = make([]v1.Reference, len(*in))
		copy(*out, *in)
	}
	if in.EndpointNamesSelector != nil {
		in, out := &in.EndpointNamesSelector, &out.EndpointNamesSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IOTHubName != nil {
		in, out := &in.IOTHubName, &out.IOTHubName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubNameRef != nil {
		in, out := &in.IOTHubNameRef, &out.IOTHubNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTHubNameSelector != nil {
		in, out := &in.IOTHubNameSelector, &out.IOTHubNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRouteParameters.
func (in *IOTHubFallbackRouteParameters) DeepCopy() *IOTHubFallbackRouteParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRouteSpec) DeepCopyInto(out *IOTHubFallbackRouteSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRouteSpec.
func (in *IOTHubFallbackRouteSpec) DeepCopy() *IOTHubFallbackRouteSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubFallbackRouteStatus) DeepCopyInto(out *IOTHubFallbackRouteStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubFallbackRouteStatus.
func (in *IOTHubFallbackRouteStatus) DeepCopy() *IOTHubFallbackRouteStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubFallbackRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubList) DeepCopyInto(out *IOTHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubList.
func (in *IOTHubList) DeepCopy() *IOTHubList {
	if in == nil {
		return nil
	}
	out := new(IOTHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubObservation) DeepCopyInto(out *IOTHubObservation) {
	*out = *in
	if in.EventHubEventsEndpoint != nil {
		in, out := &in.EventHubEventsEndpoint, &out.EventHubEventsEndpoint
		*out = new(string)
		**out = **in
	}
	if in.EventHubEventsPath != nil {
		in, out := &in.EventHubEventsPath, &out.EventHubEventsPath
		*out = new(string)
		**out = **in
	}
	if in.EventHubOperationsEndpoint != nil {
		in, out := &in.EventHubOperationsEndpoint, &out.EventHubOperationsEndpoint
		*out = new(string)
		**out = **in
	}
	if in.EventHubOperationsPath != nil {
		in, out := &in.EventHubOperationsPath, &out.EventHubOperationsPath
		*out = new(string)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.SharedAccessPolicy != nil {
		in, out := &in.SharedAccessPolicy, &out.SharedAccessPolicy
		*out = make([]SharedAccessPolicyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubObservation.
func (in *IOTHubObservation) DeepCopy() *IOTHubObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubParameters) DeepCopyInto(out *IOTHubParameters) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = make([]EndpointParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enrichment != nil {
		in, out := &in.Enrichment, &out.Enrichment
		*out = make([]EnrichmentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventHubPartitionCount != nil {
		in, out := &in.EventHubPartitionCount, &out.EventHubPartitionCount
		*out = new(float64)
		**out = **in
	}
	if in.EventHubRetentionInDays != nil {
		in, out := &in.EventHubRetentionInDays, &out.EventHubRetentionInDays
		*out = new(float64)
		**out = **in
	}
	if in.FallbackRoute != nil {
		in, out := &in.FallbackRoute, &out.FallbackRoute
		*out = make([]FallbackRouteParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileUpload != nil {
		in, out := &in.FileUpload, &out.FileUpload
		*out = make([]FileUploadParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPFilterRule != nil {
		in, out := &in.IPFilterRule, &out.IPFilterRule
		*out = make([]IPFilterRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.MinTLSVersion != nil {
		in, out := &in.MinTLSVersion, &out.MinTLSVersion
		*out = new(string)
		**out = **in
	}
	if in.PublicNetworkAccessEnabled != nil {
		in, out := &in.PublicNetworkAccessEnabled, &out.PublicNetworkAccessEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = make([]RouteParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = make([]SkuParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubParameters.
func (in *IOTHubParameters) DeepCopy() *IOTHubParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicy) DeepCopyInto(out *IOTHubSharedAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicy.
func (in *IOTHubSharedAccessPolicy) DeepCopy() *IOTHubSharedAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubSharedAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicyList) DeepCopyInto(out *IOTHubSharedAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOTHubSharedAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicyList.
func (in *IOTHubSharedAccessPolicyList) DeepCopy() *IOTHubSharedAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOTHubSharedAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicyObservation) DeepCopyInto(out *IOTHubSharedAccessPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicyObservation.
func (in *IOTHubSharedAccessPolicyObservation) DeepCopy() *IOTHubSharedAccessPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicyParameters) DeepCopyInto(out *IOTHubSharedAccessPolicyParameters) {
	*out = *in
	if in.DeviceConnect != nil {
		in, out := &in.DeviceConnect, &out.DeviceConnect
		*out = new(bool)
		**out = **in
	}
	if in.IOTHubName != nil {
		in, out := &in.IOTHubName, &out.IOTHubName
		*out = new(string)
		**out = **in
	}
	if in.IOTHubNameRef != nil {
		in, out := &in.IOTHubNameRef, &out.IOTHubNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.IOTHubNameSelector != nil {
		in, out := &in.IOTHubNameSelector, &out.IOTHubNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryRead != nil {
		in, out := &in.RegistryRead, &out.RegistryRead
		*out = new(bool)
		**out = **in
	}
	if in.RegistryWrite != nil {
		in, out := &in.RegistryWrite, &out.RegistryWrite
		*out = new(bool)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupNameRef != nil {
		in, out := &in.ResourceGroupNameRef, &out.ResourceGroupNameRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ResourceGroupNameSelector != nil {
		in, out := &in.ResourceGroupNameSelector, &out.ResourceGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceConnect != nil {
		in, out := &in.ServiceConnect, &out.ServiceConnect
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicyParameters.
func (in *IOTHubSharedAccessPolicyParameters) DeepCopy() *IOTHubSharedAccessPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicySpec) DeepCopyInto(out *IOTHubSharedAccessPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicySpec.
func (in *IOTHubSharedAccessPolicySpec) DeepCopy() *IOTHubSharedAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSharedAccessPolicyStatus) DeepCopyInto(out *IOTHubSharedAccessPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSharedAccessPolicyStatus.
func (in *IOTHubSharedAccessPolicyStatus) DeepCopy() *IOTHubSharedAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubSharedAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubSpec) DeepCopyInto(out *IOTHubSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubSpec.
func (in *IOTHubSpec) DeepCopy() *IOTHubSpec {
	if in == nil {
		return nil
	}
	out := new(IOTHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOTHubStatus) DeepCopyInto(out *IOTHubStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOTHubStatus.
func (in *IOTHubStatus) DeepCopy() *IOTHubStatus {
	if in == nil {
		return nil
	}
	out := new(IOTHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPFilterRuleObservation) DeepCopyInto(out *IPFilterRuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPFilterRuleObservation.
func (in *IPFilterRuleObservation) DeepCopy() *IPFilterRuleObservation {
	if in == nil {
		return nil
	}
	out := new(IPFilterRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPFilterRuleParameters) DeepCopyInto(out *IPFilterRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.IPMask != nil {
		in, out := &in.IPMask, &out.IPMask
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPFilterRuleParameters.
func (in *IPFilterRuleParameters) DeepCopy() *IPFilterRuleParameters {
	if in == nil {
		return nil
	}
	out := new(IPFilterRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkedHubObservation) DeepCopyInto(out *LinkedHubObservation) {
	*out = *in
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkedHubObservation.
func (in *LinkedHubObservation) DeepCopy() *LinkedHubObservation {
	if in == nil {
		return nil
	}
	out := new(LinkedHubObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkedHubParameters) DeepCopyInto(out *LinkedHubParameters) {
	*out = *in
	if in.AllocationWeight != nil {
		in, out := &in.AllocationWeight, &out.AllocationWeight
		*out = new(float64)
		**out = **in
	}
	if in.ApplyAllocationPolicy != nil {
		in, out := &in.ApplyAllocationPolicy, &out.ApplyAllocationPolicy
		*out = new(bool)
		**out = **in
	}
	out.ConnectionStringSecretRef = in.ConnectionStringSecretRef
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkedHubParameters.
func (in *LinkedHubParameters) DeepCopy() *LinkedHubParameters {
	if in == nil {
		return nil
	}
	out := new(LinkedHubParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteObservation) DeepCopyInto(out *RouteObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteObservation.
func (in *RouteObservation) DeepCopy() *RouteObservation {
	if in == nil {
		return nil
	}
	out := new(RouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteParameters) DeepCopyInto(out *RouteParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EndpointNames != nil {
		in, out := &in.EndpointNames, &out.EndpointNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteParameters.
func (in *RouteParameters) DeepCopy() *RouteParameters {
	if in == nil {
		return nil
	}
	out := new(RouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAccessPolicyObservation) DeepCopyInto(out *SharedAccessPolicyObservation) {
	*out = *in
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAccessPolicyObservation.
func (in *SharedAccessPolicyObservation) DeepCopy() *SharedAccessPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(SharedAccessPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedAccessPolicyParameters) DeepCopyInto(out *SharedAccessPolicyParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedAccessPolicyParameters.
func (in *SharedAccessPolicyParameters) DeepCopy() *SharedAccessPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(SharedAccessPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkuObservation) DeepCopyInto(out *SkuObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkuObservation.
func (in *SkuObservation) DeepCopy() *SkuObservation {
	if in == nil {
		return nil
	}
	out := new(SkuObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkuParameters) DeepCopyInto(out *SkuParameters) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkuParameters.
func (in *SkuParameters) DeepCopy() *SkuParameters {
	if in == nil {
		return nil
	}
	out := new(SkuParameters)
	in.DeepCopyInto(out)
	return out
}
