apiVersion: dbforpostgresql.azure.jet.crossplane.io/v1alpha2
kind: Configuration
metadata:
  name: example-psql-configuration
spec:
  forProvider:
    name: array_nulls
    resourceGroupNameRef:
      name: example
    serverNameRef:
      name: example-psqlserver
    value: "off"
  providerConfigRef:
    name: example