apiVersion: cache.azure.jet.crossplane.io/v1alpha2
kind: RedisLinkedServer
metadata:
  name: example-link
spec:
  forProvider:
    targetRedisCacheNameRef:
      name: example-redis
    resourceGroupNameRef:
      name: example
    linkedRedisCacheIdRef:
      name: example-redis-to-link
    linkedRedisCacheLocation: "East US"
    serverRole: "Secondary"
  providerConfigRef:
    name: example