apiVersion: keyvault.azure.crossplane.io/v1alpha1
kind: KeyVaultSecret
metadata:
  name: example
spec:
  forProvider:
    vaultBaseUrl: 'https://kv-crossplane-secrets.vault.azure.net/'
    name: crossplane-test-secret
    attributes:
      enabled: true
      notBeforeDate: '2021-09-30T00:00:00Z'
      expirationDate: '2021-09-30T00:00:00Z'
    value:
      namespace: crossplane-system
      name: example-azure-keyvault-secret
      key: value
    contentType: text/plain
    tags:
      created_by: crossplane
  providerConfigRef:
    name: example
