apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: LoadBalancer
metadata:
  name: example-lb
spec:
  forProvider:
    location: East US
    resourceGroupNameRef:
      name: example
  providerConfigRef:
    name: example