apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: example-subnet
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    virtualNetworkNameRef:
      name: example-vn
    addressPrefixes:
      - "10.0.0.0/24"
  providerConfigRef:
    name: example
