---
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: aks-example
spec:
  location: West US 2
  reclaimPolicy: Delete
  providerConfigRef:
    name: example
---
apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: aks-example
spec:
  resourceGroupNameRef:
    name: aks-example
  location: West US 2
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  reclaimPolicy: Delete
  providerConfigRef:
    name: example
---
apiVersion: network.azure.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: aks-example
spec:
  resourceGroupNameRef:
    name: aks-example
  virtualNetworkNameRef:
    name: aks-example
  properties:
    addressPrefix: 10.2.0.0/24
    serviceEndpoints:
      - service: Microsoft.Sql
  reclaimPolicy: Delete
  providerConfigRef:
    name: example
