apiVersion: eventhub.azure.jet.crossplane.io/v1alpha2
kind: ConsumerGroup
metadata:
  name: example
spec:
  forProvider:
    eventhubName: acceptanceTestEventHub
    namespaceName: example-namespace
    resourceGroupNameRef:
      name: example
    userMetadata: some-meta-data
  providerConfigRef:
    name: example
