apiVersion: eventhub.azure.jet.crossplane.io/v1alpha2
kind: EventHub
metadata:
  name: example
spec:
  forProvider:
    messageRetention: 1
    namespaceName: example
    partitionCount: 2
    resourceGroupNameRef:
      name: example
  providerConfigRef:
    name: example
