---
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: crossplane-example
spec:
  location: West US 2
  reclaimPolicy: Retain
  providerConfigRef:
    name: azure-provider
---
apiVersion: database.azure.crossplane.io/v1alpha3
kind: CosmosDBAccount
metadata:
  name: mymongoaccount
  annotations:
    crossplane.io/external-name: mymongodbaccount
spec:
  forProvider:
      resourceGroupNameRef:
        name: crossplane-example
      kind: MongoDB
      location: westus2
      properties:
        databaseAccountOfferType: Standard
        locations:
          - failoverPriority: 0
            locationName: South Central US
            isZoneRedundant: false
  providerConfigRef:
    name: azure-provider
  reclaimPolicy: Retain
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: mymongoaccountsecret