---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: example-akscluster
  labels:
    example: "true"
spec:
  resourceGroupNameRef:
    name: example-rg
  vnetSubnetIDRef:
    name: example-sub
  location: West US 2
  version: "1.21.7"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  identity:
    type: SystemAssigned
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-akscluster
