---
# Azure Admin service account secret - used by Azure Provider
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-provider-azure
type: Opaque
data:
  credentials: ewogICJjbGllbnRJZCI6ICI1ZTRkZGNlMy01Njg2LTQwNzItYmU0MC04YTUxZmVjZWY3NzgiLAogICJjbGllbnRTZWNyZXQiOiAieXQ0dTdHNFNJVzZ1bDVYSmx+NzlIemZwQ2M4Ui1SOG8tLSIsCiAgInN1YnNjcmlwdGlvbklkIjogImE1MTkxODA3LTE1YTQtNDRkYS05Y2MzLTIzNjJmNmVhNzU5ZSIsCiAgInRlbmFudElkIjogIjlhZTBhYTg5LTc1NTctNGYxYi04NjNmLWE1ZGZlMzg3NGU0MiIsCiAgImFjdGl2ZURpcmVjdG9yeUVuZHBvaW50VXJsIjogImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsCiAgInJlc291cmNlTWFuYWdlckVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5henVyZS5jb20vIiwKICAiYWN0aXZlRGlyZWN0b3J5R3JhcGhSZXNvdXJjZUlkIjogImh0dHBzOi8vZ3JhcGgud2luZG93cy5uZXQvIiwKICAic3FsTWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0Ojg0NDMvIiwKICAiZ2FsbGVyeUVuZHBvaW50VXJsIjogImh0dHBzOi8vZ2FsbGVyeS5henVyZS5jb20vIiwKICAibWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0LyIKfQo=
---
# Azure Provider with service account secret reference - used to provision cache resources
apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-azure
      key: credentials
