apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: Certificate
metadata:
  name: example-vaultcertificate
spec:
  forProvider:
    keyVaultIdRef:
      name: example-keyvault

    certificatePolicy:
    - issuerParameters:
      - name: Self

      keyProperties:
      - exportable: true
        keySize: 2048
        keyType: RSA
        reuseKey: true

      secretProperties:
      - contentType: application/x-pkcs12

      lifetimeAction:
      - action:
        - actionType: AutoRenew
        trigger:
        - daysBeforeExpiry: 30

      x509CertificateProperties:
      - extendedKeyUsage:
        - "1.3.6.1.5.5.7.3.1"
        keyUsage:
        - cRLSign
        - dataEncipherment
        - digitalSignature
        - keyAgreement
        - keyCertSign
        - keyEncipherment
        subjectAlternativeNames:
        - dnsNames:
          - crossplane.io
        subject: CN=crossplane
        validityInMonths: 12

  providerConfigRef:
    name: example