apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: Key
metadata:
  name: example-vaultkey
spec:
  forProvider:
    keyVaultIdRef:
      name: example-keyvault

    keyOpts:
    - decrypt
    - encrypt
    - sign
    - unwrapKey
    - verify
    - wrapKey
    keySize: 2048
    keyType: RSA

  providerConfigRef:
    name: example