apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: ManagedStorageAccount
metadata:
  name: examplemanagedstorage # This field must be between 3-24 characters.
  # If a name longer than 24 characters is used, Azure SDK returns a misleading HTTP 404 error.
  # For details please check the following issue: https://github.com/crossplane-contrib/provider-jet-azure/issues/128
spec:
  forProvider:
    keyVaultIdRef:
      name: example-keyvault
    storageAccountIdRef:
      name: example-storage-account
    storageAccountKey: key1
    regenerateKeyAutomatically: false
    regenerationPeriod: P1D
  providerConfigRef:
    name: example