apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: ManagedStorageAccountSASTokenDefinition
metadata:
  name: examplesasdefinition
spec:
  forProvider:
    validityPeriod: P1D
    managedStorageAccountIdRef:
      name: examplemanagedstorage
    sasTemplateUri: <sas_token>
    sasType: account
  providerConfigRef:
    name: example