apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: Secret
metadata:
  name: example-vaultsecret
spec:
  forProvider:
    keyVaultIdRef:
      name: example-keyvault

    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system

  providerConfigRef:
    name: example
