apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: Vault
metadata:
  name: example-keyvault
spec:
  forProvider:
    enabledForDiskEncryption: true
    location: West Europe
    purgeProtectionEnabled: false
    resourceGroupNameRef:
      name: example
    skuName: standard
    softDeleteRetentionDays: 7
    tenantId: <tenant id>
  providerConfigRef:
    name: example