---
apiVersion: database.azure.crossplane.io/v1beta1
kind: MySQLServer
metadata:
  name: example-mysql
  labels:
    example: "true"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: example-rg
    location: West US 2
    minimalTlsVersion: TLS1_2
    sslEnforcement: Enabled
    version: "5.7"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-mysql
  providerConfigRef:
    name: example
