apiVersion: devices.azure.jet.crossplane.io/v1alpha2
kind: IOTHubFallbackRoute
metadata:
  name: example
spec:
  forProvider:
    condition: "true"
    enabled: true
    endpointNames:
    - ${azurerm_iothub_endpoint_storage_container.example.name}
    iothubName: ${azurerm_iothub.example.name}
    resourceGroupNameRef:
      name: example
  providerConfigRef:
    name: example
