---
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: example-psql
  labels:
    example: "true"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: example-rg
    location: West US 2
    sslEnforcement: Disabled
    version: "9.6"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretsToRef:
    namespace: crossplane-system
    name: example-psql
  providerConfigRef:
    name: example
