apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-azure
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane/provider-azure
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The Microsoft Azure Crossplane provider adds support for managing Azure
      resources in Kubernetes.
    meta.crossplane.io/readme: |
      `provider-azure` is the Crossplane infrastructure provider for [Microsoft
      Azure](https://azure.microsoft.com/).

      If you encounter an issue please reach out on
      [slack.crossplane.io](https://slack.crossplane.io) and create an issue in
      the [crossplane/provider-azure](https://github.com/crossplane/provider-azure)
      repo.
spec:
  controller:
    image: crossplane/provider-azure-controller:VERSION
