apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
kind: KubernetesClusterNodePool
metadata:
  name: example-nodepool
  annotations:
    crossplane.io/external-name: nodepool1
spec:
  forProvider:
    kubernetesClusterId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/example/providers/Microsoft.ContainerService/managedClusters/example-aks"
    vmSize: "Standard_DS2_v2"
    nodeCount: 1
    tags:
      purpose: example
  providerConfigRef:
    name: example